version: '3.7'

services:
  webp-to-gif-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: webp-to-gif-service:latest
    container_name: webp-to-gif-service
    volumes:
      - ".:/app"
