version: '3.7'

services:
  webp-to-gif-service:
    build:
      context: ./webp-to-gif-service
      dockerfile: ./Dockerfile
    image: webp-to-gif-service:latest
    container_name: webp-to-gif-service
    volumes:
      - "./data:/app/data"
